-- ============================================================
-- CORREÇÃO / MIGRAÇÃO DA ESTRUTURA
-- PRÉ-IMPLANTAÇÃO
-- ============================================================

create extension if not exists "pgcrypto";


-- ============================================================
-- 1. VISTORIADORES
-- ============================================================

create table if not exists public.vistoriadores (
    id bigint generated by default as identity primary key,
    nome text not null,
    funcao text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 2. VISTORIAS
-- ============================================================

create table if not exists public.vistorias (
    id uuid primary key default gen_random_uuid(),
    local text not null default 'Hospital Base',
    vistoriador_id bigint null,
    respostas jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 3. ADICIONAR COLUNAS QUE POSSAM ESTAR FALTANDO
-- ============================================================

alter table public.vistorias
add column if not exists status text
default 'em_andamento';

alter table public.vistorias
add column if not exists finalizada_at timestamptz;

alter table public.vistorias
add column if not exists updated_at timestamptz
default now();

alter table public.vistorias
add column if not exists respostas jsonb
default '{}'::jsonb;

alter table public.vistorias
add column if not exists local text
default 'Hospital Base';

alter table public.vistorias
add column if not exists vistoriador_id bigint;


-- ============================================================
-- 4. GARANTIR DEFAULTS
-- ============================================================

alter table public.vistorias
alter column respostas set default '{}'::jsonb;

alter table public.vistorias
alter column status set default 'em_andamento';

alter table public.vistorias
alter column updated_at set default now();


-- ============================================================
-- 5. CORRIGIR POSSÍVEIS VALORES NULOS
-- ============================================================

update public.vistorias
set status = 'em_andamento'
where status is null;

update public.vistorias
set respostas = '{}'::jsonb
where respostas is null;

update public.vistorias
set updated_at = now()
where updated_at is null;


-- ============================================================
-- 6. FOREIGN KEY
-- ============================================================

do $$
begin

    if not exists (
        select 1
        from pg_constraint
        where conname = 'vistorias_vistoriador_id_fkey'
    ) then

        alter table public.vistorias
        add constraint vistorias_vistoriador_id_fkey
        foreign key (vistoriador_id)
        references public.vistoriadores(id)
        on delete set null;

    end if;

end $$;


-- ============================================================
-- 7. CONSTRAINT STATUS
-- ============================================================

do $$
begin

    if not exists (
        select 1
        from pg_constraint
        where conname = 'vistorias_status_check'
    ) then

        alter table public.vistorias
        add constraint vistorias_status_check
        check (
            status in (
                'em_andamento',
                'finalizada',
                'cancelada'
            )
        );

    end if;

end $$;


-- ============================================================
-- 8. ÍNDICES
-- ============================================================

create index if not exists idx_vistoriadores_nome
on public.vistoriadores(nome);

create index if not exists idx_vistorias_vistoriador
on public.vistorias(vistoriador_id);

create index if not exists idx_vistorias_status
on public.vistorias(status);

create index if not exists idx_vistorias_created_at
on public.vistorias(created_at desc);

create index if not exists idx_vistorias_respostas
on public.vistorias using gin(respostas);


-- ============================================================
-- 9. FUNÇÃO updated_at
-- ============================================================

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


-- ============================================================
-- 10. TRIGGER VISTORIADORES
-- ============================================================

drop trigger if exists update_vistoriadores_updated_at
on public.vistoriadores;

create trigger update_vistoriadores_updated_at
before update on public.vistoriadores
for each row
execute function public.update_updated_at_column();


-- ============================================================
-- 11. TRIGGER VISTORIAS
-- ============================================================

drop trigger if exists update_vistorias_updated_at
on public.vistorias;

create trigger update_vistorias_updated_at
before update on public.vistorias
for each row
execute function public.update_updated_at_column();


-- ============================================================
-- 12. RLS VISTORIADORES
-- ============================================================

alter table public.vistoriadores
enable row level security;


drop policy if exists "vistoriadores_select_public"
on public.vistoriadores;

create policy "vistoriadores_select_public"
on public.vistoriadores
for select
to anon, authenticated
using (true);


drop policy if exists "vistoriadores_insert_public"
on public.vistoriadores;

create policy "vistoriadores_insert_public"
on public.vistoriadores
for insert
to anon, authenticated
with check (true);


drop policy if exists "vistoriadores_update_public"
on public.vistoriadores;

create policy "vistoriadores_update_public"
on public.vistoriadores
for update
to anon, authenticated
using (true)
with check (true);


-- ============================================================
-- 13. RLS VISTORIAS
-- ============================================================

alter table public.vistorias
enable row level security;


drop policy if exists "vistorias_select_public"
on public.vistorias;

create policy "vistorias_select_public"
on public.vistorias
for select
to anon, authenticated
using (true);


drop policy if exists "vistorias_insert_public"
on public.vistorias;

create policy "vistorias_insert_public"
on public.vistorias
for insert
to anon, authenticated
with check (true);


drop policy if exists "vistorias_update_public"
on public.vistorias;

create policy "vistorias_update_public"
on public.vistorias
for update
to anon, authenticated
using (true)
with check (true);


-- ============================================================
-- 14. STORAGE
-- ============================================================

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'fotos_vistorias',
    'fotos_vistorias',
    true,
    10485760,
    array[
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/heic',
        'image/heif'
    ]
)
on conflict (id) do nothing;


-- ============================================================
-- 15. STORAGE - LEITURA
-- ============================================================

drop policy if exists "fotos_vistorias_select_public"
on storage.objects;

create policy "fotos_vistorias_select_public"
on storage.objects
for select
to anon, authenticated
using (
    bucket_id = 'fotos_vistorias'
);


-- ============================================================
-- 16. STORAGE - UPLOAD
-- ============================================================

drop policy if exists "fotos_vistorias_insert_public"
on storage.objects;

create policy "fotos_vistorias_insert_public"
on storage.objects
for insert
to anon, authenticated
with check (
    bucket_id = 'fotos_vistorias'
);


-- ============================================================
-- 17. STORAGE - UPDATE
-- ============================================================

drop policy if exists "fotos_vistorias_update_public"
on storage.objects;

create policy "fotos_vistorias_update_public"
on storage.objects
for update
to anon, authenticated
using (
    bucket_id = 'fotos_vistorias'
)
with check (
    bucket_id = 'fotos_vistorias'
);


-- ============================================================
-- 18. STORAGE - DELETE
-- ============================================================

drop policy if exists "fotos_vistorias_delete_public"
on storage.objects;

create policy "fotos_vistorias_delete_public"
on storage.objects
for delete
to anon, authenticated
using (
    bucket_id = 'fotos_vistorias'
);


-- ============================================================
-- 19. VISTORIADORES INICIAIS
-- ============================================================

insert into public.vistoriadores (nome, funcao)
select 'Darlet Avelar', 'Engenheiro'
where not exists (
    select 1
    from public.vistoriadores
    where nome = 'Darlet Avelar'
);

insert into public.vistoriadores (nome, funcao)
select 'José Pedro', 'Engenheiro'
where not exists (
    select 1
    from public.vistoriadores
    where nome = 'José Pedro'
);

insert into public.vistoriadores (nome, funcao)
select 'Lyvio Nascimento', 'Engenheiro'
where not exists (
    select 1
    from public.vistoriadores
    where nome = 'Lyvio Nascimento'
);

insert into public.vistoriadores (nome, funcao)
select 'Michelle Machado', 'Engenheira'
where not exists (
    select 1
    from public.vistoriadores
    where nome = 'Michelle Machado'
);


-- ============================================================
-- 20. VERIFICAÇÃO
-- ============================================================

select
    table_name,
    column_name,
    data_type
from information_schema.columns
where table_schema = 'public'
and table_name in ('vistoriadores', 'vistorias')
order by table_name, ordinal_position;